### ISSUE TITLE
Other brand bms want to use esphome

### ISSUE THREAD

**Issue by shum-elli** [syssi/esphome-lolan-bms#1]
I want to adapte lolan bms to esphome，but i meet some problems，Could you help me to analysis

**Comment by syssi** [comment]
I've started the implementation but it's in early stage.

**Comment by syssi** [comment]
```
const { buffer } = new Uint8Array([65,184,230,184]);
const dataview = new DataView(buffer);
console.log(dataview.getFloat32(0))
> 23.112655639648438
```

**Comment by shum-elli** [comment]
Wow. Even opened a separate project. Thank you very much for helping me.

**Comment by shum-elli** [comment]
> ```
> const { buffer } = new Uint8Array([65,184,230,184]);
> const dataview = new DataView(buffer);
> console.log(dataview.getFloat32(0))
> > 23.112655639648438
> ```

I think this is the write data.

**Comment by shum-elli** [comment]
But for me,the most difficult problem is how to get value,I'm puzzled at how to communicate with BMS.I'm a bluetooth newbie.

**Comment by shum-elli** [comment]
I could provide usb share service(bluetooth  device) or remote desktop to help debug

**Comment by shum-elli** [comment]
Wow, I get ,c56500bc614e this is the get data command.

**Comment by syssi** [comment]
Could you prepare another btsnoop capture of the other views? It looks like we are retrieving the status frame only at the moment. There should be a `cell voltages` frame and a `settings` frame too. Could you also trigger the mosfet switches a few times?

I will implement the decoder later the week. At the moment the floats aren't decided properly.

**Comment by shum-elli** [comment]
I have done some capture to cap this command.  MOSFET I have tested. It's right. Maybe I think settings is not necessary to use esphome

5b6500bc614e , this is the cell voltage view command
860000bc614e , turn off discharge
855500bc614e , turn on discharge
d88800bc614e , turn on charge
d90000bc614e , turn off charge

[btsnoop_hci_20240624_132911.zip](https://github.com/user-attachments/files/15950376/btsnoop_hci_20240624_132911.zip)
![image](https://github.com/syssi/esphome-lolan-bms/assets/79710429/8ac6a5cd-c0f4-46de-be71-84720a18b553)

**Comment by syssi** [comment]
How many cells does the BMS support? Could you provide the model name of your BMS and/or a photo?

**Comment by shum-elli** [comment]
6-8 cells  
![image](https://github.com/syssi/esphome-lolan-bms/assets/79710429/03a58cd1-f0d1-48e7-8641-3693278409aa)

**Comment by syssi** [comment]
Does the capture include a settings frame too? I would like to print the settings into the log.

**Comment by syssi** [comment]
This ESPHome helper method should be used to decode the float32 measurements:

```
float converted_value = esphome::decode_float(bytes);
```

**Comment by shum-elli** [comment]
[2024-06-24-15-12-13.zip](https://github.com/user-attachments/files/15951215/2024-06-24-15-12-13.zip)
settings view is complex，i record my operation

**Comment by syssi** [comment]
The component is able to decode the `status frame` now. Please give it a try! :-) 

```
[20:42:39][I][lolan_bms_ble:122]: Status frame received
[20:42:39][D][lolan_bms_ble:123]:   01.00.02.00.41.B9.02.90.00.00.00.00.00.00.00.00.41.D7.D9.B0.41.CD.60.00.42.9D.93.20.42.47.9E.44.00.36.3E.5A.00.01.00.27 (40)
[20:42:39][I][lolan_bms_ble:129]:   Switch bitmask: 2
[20:42:39][I][lolan_bms_ble:132]:   Status bitmask: 0
[20:42:39][I][lolan_bms_ble:135]:   Total voltage: 23.13 V
[20:42:39][I][lolan_bms_ble:140]:   Current: 0.00 A
[20:42:39][I][lolan_bms_ble:141]:   Current: 0.00 A
[20:42:39][I][lolan_bms_ble:144]:   Temperature 1: 26.98 °C
[20:42:39][I][lolan_bms_ble:147]:   Temperature 2: 25.67 °C
[20:42:39][I][lolan_bms_ble:150]:   Total discharging energy: 78.79 Ah
[20:42:39][I][lolan_bms_ble:153]:   Total charging energy: 49.90 Ah
[20:42:39][I][lolan_bms_ble:156]:   Total runtime: 3554906 S
[20:42:39][I][lolan_bms_ble:157]:   Total runtime: 41d 3h
[20:42:39][I][lolan_bms_ble:160]:   Charging cycles: 1
[20:42:39][I][lolan_bms_ble:163]:   State of charge: 39 %
```

**Comment by shum-elli** [comment]
Very good progress. I've tried this.And I've get the right date.
![image](https://github.com/syssi/esphome-lolan-bms/assets/79710429/ef117a6f-b06a-4374-aa6b-1c59faacca64)

**Comment by syssi** [comment]
Perfect! The measurements aren't published yet. The `NA` states at the web interface are fine for now.

**Comment by shum-elli** [comment]
Much obliged.

**Comment by syssi** [comment]
Could you tell me the password / pin number which is required if you use the app?

The update version is able to publish some measurements now. Please update your YAML.

**Comment by shum-elli** [comment]
The default password is “12345678”.

**Comment by shum-elli** [comment]
Convert to hex is “bc614e”，the end of the command

**Comment by shum-elli** [comment]
![44ead039a53483d0fdd29c84cd20084](https://github.com/syssi/esphome-lolan-bms/assets/79710429/4dfed9bb-65ab-4b2b-953a-330b5e12f320)

I've test discharge.The current is right,But the power is zero.I think it's not a big problem,just multipy current & voltage.I've read some code in seller's program,It obtained by this way. About charge, I need wait until tomorrow and test.Because now the sun has set，PV board doesn't work.

**Comment by syssi** [comment]
I know what's going on. I will fix the power sensor tomorrow.

**Comment by shum-elli** [comment]
Got it.Today I've tested charging. The charge current & power is all right. 
![image](https://github.com/syssi/esphome-lolan-bms/assets/79710429/e2a554cd-53b2-4f6e-87b2-5cdc0cbbfe86)

**Comment by syssi** [comment]
The component is able to publish the most important measurements now. Please update your YAML and give it another try!

**Comment by syssi** [comment]
I have to ask again: Did you make the btsnoop captures using the wechat mini program or the second obfuscated app?

**Comment by shum-elli** [comment]
Actually，I use  the second obfuscated app to make the btsnoop captures, if you need i can make a new one for you.The capture
 phone doesn't login wechat, so i use the second app like the screen capture do.

**Comment by syssi** [comment]
I'm asking because the request payloads of the wechat app doesn't match exactly with the captured payloads. No action needed. I will use the captured commands to be safe.

Could you capture the reset of the different counters too? There should be a button to reset the charging cycle counter and the total charged/discharged energy counter.

**Comment by shum-elli** [comment]
I have searched everywhere in wechat miniprogram & app , I don't find a button or other way to restore the counter. I think maybe it is not supported. ┭┮﹏┭┮

**Comment by syssi** [comment]
It's supported by this implementation now. Please update your YAML and to a clean build. The Mosfets can be controlled now and some counters can be resetted using buttons. Please don't test the `factory reset`. ;-)

**Comment by shum-elli** [comment]
Except factory reset, I have test all button  function is right, But I think it lacks two data,  total charging energy &  total discharging energy, I have saw them in log output, but i don't see config in sensor.py

**Comment by syssi** [comment]
I will add these sensors soon.

**Comment by syssi** [comment]
The basic implementation is complete now. Feel free to create new issues if you miss something!

**Comment by syssi** [comment]
I'm still playing around. Could you provide some more settings frames? They can be retrieve using the `retrieve settings button` if you don't want to do another btsnoop capture.

**Comment by shum-elli** [comment]
> 我还在玩。你能提供更多的设置框架吗？如果您不想再进行一次 btsnoop 捕获，可以使用 来检索它们。`retrieve settings button`

Tomorrow I  will take a  btsnoop capture again.

**Comment by syssi** [comment]
Thanks!

**Comment by shum-elli** [comment]
https://drive.google.com/file/d/1P6zqe02axp4mUClfG7xCjVYJqLPksznm/view?usp=sharing

It was too hot during the day, so I collected this data after dinner.The file has included screen record, So it  exceed github file upload limit,I upload it to google cloud.

**Comment by syssi** [comment]
```
03:6c:00:bc:61:4e:0c:00:00:32:00:50:08:0f:07:01:ff:fa:00:02:42:51:09:41:40:56:66:66:3f:80:00:00:40:b7:95:81:40:b2:b8:52:41:9a:00:00:41:cc:00:00:40:30:00:00:40:69:99:9a:42:82:00:00:42:82:00:00:46:1c:40:00:cc:10:f1:52:01:34:8b:9a:40:30:00:00:40:53:33:33:3c:23:d7:0a:41:c0:cc:cd:40:5c:cc:cd:41:a2:66:66:40:39:99:9a:5d:c4:5a:a5

03:6c:05:39:7f:b1:0c:00:00:32:00:50:08:0f:07:01:ff:fa:00:02:42:51:09:41:40:56:66:66:3f:80:00:00:40:b7:95:81:40:b2:b8:52:41:99:99:9a:41:cc:00:00:40:30:00:00:40:6a:3d:71:42:82:00:00:42:82:00:00:46:1c:40:00:cc:10:f1:52:01:34:8b:9a:40:30:00:00:40:53:33:33:3c:23:d7:0a:41:c0:cc:cd:40:5c:cc:cd:41:a2:66:66:40:39:99:9a:13:f4:5a:a5
```

Thanks!
